#!/usr/bin/env bash
# Import an external GitHub repository as a git submodule under third_party/
# and wire it into the right HA-native directory based on its kind.
#
# Usage:
#   scripts/import-repo.sh <github-url> <kind> [<name>]
#     kind = blueprint | package | dashboard | other
#
# Examples:
#   scripts/import-repo.sh https://github.com/example/awesome-blueprints blueprint awesome
#   scripts/import-repo.sh https://github.com/example/lights-package package lights
#
# What it does:
#   - Adds the URL as a submodule at third_party/<name>.
#   - blueprint -> symlink blueprints/automation/<name> -> ../../third_party/<name>
#   - package   -> create packages/<name>.yaml with !include third_party/<name>/<entrypoint>.yaml
#                  (fallback: symlink packages/<name> -> ../third_party/<name>)
#   - dashboard -> leave wiring to the user (printed instructions)
#   - other     -> submodule only

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <github-url> <kind> [<name>]" >&2
  exit 2
fi

url="$1"
kind="$2"
name="${3:-}"
if [[ -z "${name}" ]]; then
  name="$(basename "${url%.git}")"
fi

repo_root="$(git rev-parse --show-toplevel)"
cd "${repo_root}"

target="third_party/${name}"
if [[ -e "${target}" ]]; then
  echo "${target} already exists; pulling latest from upstream..."
  git submodule update --init --remote -- "${target}"
else
  echo "Adding submodule ${url} -> ${target}"
  git submodule add "${url}" "${target}"
  git submodule update --init --recursive -- "${target}"
fi

case "${kind}" in
  blueprint)
    link="blueprints/automation/${name}"
    mkdir -p "$(dirname "${link}")"
    if [[ ! -e "${link}" ]]; then
      ln -s "../../third_party/${name}" "${link}"
      echo "Linked ${link} -> ../../third_party/${name}"
    fi
    ;;
  package)
    pkg="packages/${name}.yaml"
    entry=""
    for cand in "${target}/package.yaml" "${target}/packages.yaml" "${target}/${name}.yaml"; do
      [[ -f "${cand}" ]] && { entry="${cand#"${repo_root}/"}"; break; }
    done
    if [[ -n "${entry}" ]]; then
      printf '%s\n' "# Auto-generated by scripts/import-repo.sh; edit if upstream layout changes." \
                   "${name}: !include ../${entry}" > "${pkg}"
      echo "Wrote ${pkg}"
    else
      link="packages/${name}"
      if [[ ! -e "${link}" ]]; then
        ln -s "../third_party/${name}" "${link}"
        echo "Linked ${link} -> ../third_party/${name} (no obvious entrypoint found)"
      fi
    fi
    ;;
  dashboard)
    echo "Submodule added at ${target}."
    echo "Wire it manually into a dashboards/<name>.yaml with !include ../third_party/${name}/<file>.yaml"
    ;;
  other)
    echo "Submodule added at ${target}. No automatic wiring (kind=other)."
    ;;
  *)
    echo "Unknown kind '${kind}'. Use: blueprint | package | dashboard | other" >&2
    exit 2
    ;;
esac

echo
echo "Don't forget:"
echo "  git add .gitmodules ${target} blueprints packages dashboards 2>/dev/null || true"
echo "  git commit -m 'import(${kind}): ${name} from ${url}'"
echo "  git push"
echo "Then trigger a Git Pull on the Green (SSH; HTTP proxy 401s):"
echo "  ssh root@\${HA_HOST%%:*} -p 22222 'ha addons start core_git_pull'"
